#spring:
#  datasource:
#    url: jdbc:mysql:///springboot?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong  
#    username: root
#    password: 123456

spring:
  profiles:
    active: dev
---
spring:
      application:
                 name: config-dev
      profiles: dev
 
 
---
spring:
  application:
    name: config-test
  profiles: test       
    
